# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170123_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='desc',
        ),
        migrations.AddField(
            model_name='developer',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
