# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170123_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_bar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
